const ALLOWED_EMAIL_DOMAINS = new Set([
  'gmail.com',
  'googlemail.com',
  'outlook.com',
  'outlook.com.ar',
  'outlook.com.au',
  'outlook.com.br',
  'outlook.co.id',
  'outlook.co.il',
  'outlook.co.nz',
  'outlook.co.th',
  'outlook.sa',
  'outlook.sg',
  'outlook.cl',
  'outlook.in',
  'outlook.ie',
  'outlook.pt',
  'outlook.be',
  'outlook.at',
  'outlook.cz',
  'outlook.dk',
  'outlook.hu',
  'outlook.gr',
  'outlook.de',
  'outlook.es',
  'outlook.fr',
  'outlook.it',
  'outlook.jp',
  'outlook.kr',
  'hotmail.com',
  'hotmail.co.uk',
  'hotmail.fr',
  'hotmail.it',
  'hotmail.de',
  'hotmail.es',
  'hotmail.com.br',
  'hotmail.com.ar',
  'hotmail.com.au',
  'hotmail.co.jp',
  'hotmail.nl',
  'hotmail.se',
  'hotmail.be',
  'hotmail.ca',
  'hotmail.ch',
  'hotmail.co.nz',
  'hotmail.co.th',
  'hotmail.co.za',
  'hotmail.com.mx',
  'hotmail.com.tr',
  'hotmail.dk',
  'hotmail.fi',
  'hotmail.no',
  'live.com',
  'live.co.uk',
  'live.com.au',
  'live.ca',
  'live.cn',
  'live.de',
  'live.fr',
  'live.it',
  'live.jp',
  'live.nl',
  'live.se',
  'msn.com',
  'passport.com',
  'windowslive.com',
  'yahoo.com',
  'ymail.com',
  'rocketmail.com',
  'yahoo.co.uk',
  'yahoo.fr',
  'yahoo.de',
  'yahoo.it',
  'yahoo.es',
  'yahoo.ca',
  'yahoo.com.au',
  'yahoo.co.jp',
  'yahoo.co.in',
  'yahoo.co.id',
  'yahoo.com.br',
  'yahoo.com.mx',
  'yahoo.com.ar',
  'yahoo.com.sg',
  'yahoo.com.hk',
  'yahoo.com.tw',
  'yahoo.co.kr',
  'yahoo.in',
  'yahoo.ie',
  'yahoo.com.ph',
  'yahoo.com.vn',
  'yahoo.com.my',
  'yahoo.co.nz',
  'yahoo.nl',
  'yahoo.se',
  'yahoo.no',
  'yahoo.dk',
  'icloud.com',
  'me.com',
  'mac.com',
  'qq.com',
  'foxmail.com',
  'vip.qq.com',
  '163.com',
  '126.com',
  'yeah.net',
  'vip.163.com',
  'vip.126.com',
  '188.com',
  'sina.com',
  'sina.cn',
  'vip.sina.com',
  'vip.sina.cn',
  '2008.sina.com',
  '51uc.com',
  'proton.me',
  'protonmail.com',
  'protonmail.ch',
  'pm.me',
  'aol.com',
  'aim.com',
  'mail.ru',
  'bk.ru',
  'inbox.ru',
  'list.ru',
  'internet.ru',
  'xmail.ru',
  'mail.ua',
  'yandex.com',
  'yandex.ru',
  'ya.ru',
  'gmx.com',
  'gmx.net',
  'gmx.de',
  'web.de',
  'naver.com',
  'daum.net',
  'hanmail.net',
  'nease.net',
])

const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

export function normalizeEmail(email: string | null | undefined): string | null {
  if (!email || typeof email !== 'string') return null
  const normalized = email.trim().toLowerCase()
  if (!EMAIL_REGEX.test(normalized) || normalized.length > 254) return null
  return normalized
}

export function emailDomain(email: string): string {
  return email.slice(email.lastIndexOf('@') + 1).toLowerCase()
}

export function isAllowedEmailDomain(email: string): boolean {
  return ALLOWED_EMAIL_DOMAINS.has(emailDomain(email))
}

export function allowedEmailDomains(): string[] {
  return [...ALLOWED_EMAIL_DOMAINS].sort()
}
